# Generated by Django 5.0.3 on 2024-03-06 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_alter_usersocial_user_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSocial',
        ),
    ]
