# Generated by Django 5.0.3 on 2024-03-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersocial',
            name='social_auth',
        ),
        migrations.AddField(
            model_name='usersocial',
            name='data',
            field=models.CharField(default='None', max_length=99999),
        ),
    ]
