# Generated by Django 5.0.3 on 2024-03-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_usersocial_social_auth_usersocial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersocial',
            name='page_id',
            field=models.IntegerField(default=0, max_length=999),
        ),
    ]
